In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", None)

In [2]:
cohort = pd.read_csv("../data/hf_dataset/sepsis_cohort.csv")
diagnosis = pd.read_csv("../data/hf_dataset/sepsis_diagnoses_icd.csv")
timeseries = pd.read_csv("../data/hf_dataset/sepsis_timeseries_hourly.csv")
time_comparison = pd.read_csv("../data/hf_dataset/sepsis_time_comparison.csv")

datasets = {
    "Cohort": cohort,
    "Diagnosis": diagnosis,
    "Timeseries": timeseries,
    "Time Comparison": time_comparison
}
for name , df in datasets.items():
    print("=" * 80)
    print(name)
    print("\nshape:")
    print(df.shape)
    print("\ncolumns:")
    print(df.columns.tolist())
    print("\ninfo:")
    print(df.info())

================================================================================
Cohort

shape:
(32971, 12)

columns:
['subject_id', 'hadm_id', 'stay_id', 'icu_intime', 'icu_outtime', 'sepsis_time', 'suspected_infection_time', 'window_end_uncapped', 'window_end', 'gender', 'age', 'n_hours']

info:
<class 'pandas.DataFrame'>
RangeIndex: 32971 entries, 0 to 32970
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   subject_id                32971 non-null  int64
 1   hadm_id                   32971 non-null  int64
 2   stay_id                   32971 non-null  int64
 3   icu_intime                32971 non-null  str
 4   icu_outtime               32971 non-null  str
 5   sepsis_time               32971 non-null  str
 6   suspected_infection_time  32971 non-null  str
 7   window_end_uncapped       32971 non-null  str
 8   window_end                32971 non-null  str
 9   gender                    32971 non-null  str
 10  age                       32971 non-null  int64
 11  n_hours                   32971 non-null  int64
dtypes: int64(5), str(7)
memory usage: 6.6 MB
None
================================================================================
Diagnosis

shape:
(673435, 5)

columns:
['stay_id', 'hadm_id', 'seq_num', 'icd_code', 'icd_version']

info:
<class 'pandas.DataFrame'>
RangeIndex: 673435 entries, 0 to 673434
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   stay_id      673435 non-null  int64
 1   hadm_id      673435 non-null  int64
 2   seq_num      673435 non-null  int64
 3   icd_code     673435 non-null  str
 4   icd_version  673435 non-null  int64
dtypes: int64(4), str(1)
memory usage: 30.2 MB
None
================================================================================
Timeseries

shape:
(851717, 64)

columns:
['stay_id', 'hour', 'heart_rate', 'resp_rate', 'temperature', 'sbp', 'dbp', 'mbp', 'spo2', 'gcs', 'urineoutput_last', 'urineoutput_sum', 'wbc', 'hemoglobin', 'hematocrit', 'platelet', 'creatinine', 'bun', 'sodium', 'potassium', 'chloride', 'bicarbonate', 'calcium', 'aniongap', 'glucose_lab', 'albumin', 'bilirubin_total', 'inr', 'pt', 'ptt', 'lactate', 'bands', 'crp', 'magnesium', 'starttime', 'endtime', 'pao2fio2ratio_novent', 'pao2fio2ratio_vent', 'rate_epinephrine', 'rate_norepinephrine', 'rate_dopamine', 'rate_dobutamine', 'meanbp_min', 'gcs_min', 'urineoutput_24hr', 'uo_tm_24hr', 'uo_24hr', 'bilirubin_max', 'creatinine_max', 'platelet_min', 'respiration', 'coagulation', 'liver', 'cardiovascular', 'cns', 'renal', 'sofa_score', 'respiration_24hours', 'coagulation_24hours', 'liver_24hours', 'cardiovascular_24hours', 'cns_24hours', 'renal_24hours', 'sofa_24hours']

info:
<class 'pandas.DataFrame'>
RangeIndex: 851717 entries, 0 to 851716
Data columns (total 64 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   stay_id                 851717 non-null  int64
 1   hour                    851717 non-null  int64
 2   heart_rate              796313 non-null  float64
 3   resp_rate               792053 non-null  float64
 4   temperature             265583 non-null  float64
 5   sbp                     779194 non-null  float64
 6   dbp                     779038 non-null  float64
 7   mbp                     779961 non-null  float64
 8   spo2                    783394 non-null  float64
 9   gcs                     246431 non-null  float64
 10  urineoutput_last        504531 non-null  float64
 11  urineoutput_sum         504531 non-null  float64
 12  wbc                     78378 non-null   float64
 13  hemoglobin              79690 non-null   float64
 14  hematocrit              91063 non-null   float64
 15  platelet                80261 non-null   float64
 16  creatinine              80524 non-null   float64
 17  bun                     80329 non-null   float64
 18  sodium                  83930 non-null   float64
 19  potassium               84698 non-null   float64
 20  chloride                84299 non-null   float64
 21  bicarbonate             80189 non-null   float64
 22  calcium                 69205 non-null   float64
 23  aniongap                79152 non-null   float64
 24  glucose_lab             75464 non-null   float64
 25  albumin                 14423 non-null   float64
 26  bilirubin_total         26449 non-null   float64
 27  inr                     59599 non-null   float64
 28  pt                      59614 non-null   float64
 29  ptt                     61112 non-null   float64
 30  lactate                 62683 non-null   float64
 31  bands                   5701 non-null    float64
 32  crp                     724 non-null     float64
 33  magnesium               73909 non-null   float64
 34  starttime               851717 non-null  str
 35  endtime                 851717 non-null  str
 36  pao2fio2ratio_novent    8647 non-null    float64
 37  pao2fio2ratio_vent      52289 non-null   float64
 38  rate_epinephrine        20246 non-null   float64
 39  rate_norepinephrine     123937 non-null  float64
 40  rate_dopamine           10522 non-null   float64
 41  rate_dobutamine         6496 non-null    float64
 42  meanbp_min              781057 non-null  float64
 43  gcs_min                 246973 non-null  float64
 44  urineoutput_24hr        505456 non-null  float64
 45  uo_tm_24hr              505456 non-null  float64
 46  uo_24hr                 66879 non-null   float64
 47  bilirubin_max           26466 non-null   float64
 48  creatinine_max          80601 non-null   float64
 49  platelet_min            80333 non-null   float64
 50  respiration             60907 non-null   float64
 51  coagulation             80333 non-null   float64
 52  liver                   26466 non-null   float64
 53  cardiovascular          784562 non-null  float64
 54  cns                     246973 non-null  float64
 55  renal                   142244 non-null  float64
 56  sofa_score              800765 non-null  float64
 57  respiration_24hours     851717 non-null  int64
 58  coagulation_24hours     851717 non-null  int64
 59  liver_24hours           851717 non-null  int64
 60  cardiovascular_24hours  851717 non-null  int64
 61  cns_24hours             851717 non-null  int64
 62  renal_24hours           851717 non-null  int64
 63  sofa_24hours            851717 non-null  int64
dtypes: float64(53), int64(9), str(2)
memory usage: 446.7 MB
None
================================================================================
Time Comparison

shape:
(32971, 16)

columns:
['stay_id', 'icu_intime', 'icu_intime_floor', 'cohort_sepsis_time', 'suspected_infection_time', 'suspected_infection_hour_from_intime_floor', 'cohort_sepsis_hour_from_intime_floor', 'spesis_hour_delta2', 'spesis_time_delta2', 'diff_hours_delta2', 'spesis_hour_sofa2', 'spesis_time_sofa2', 'diff_hours_sofa2', 'sepsis3_endtime', 'sepsis3_time_hour_floor', 'diff_hours_sepsis3']

info:
<class 'pandas.DataFrame'>
RangeIndex: 32971 entries, 0 to 32970
Data columns (total 16 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   stay_id                                     32971 non-null  int64
 1   icu_intime                                  32971 non-null  str
 2   icu_intime_floor                            32971 non-null  str
 3   cohort_sepsis_time                          32971 non-null  str
 4   suspected_infection_time                    32971 non-null  str
 5   suspected_infection_hour_from_intime_floor  32971 non-null  int64
 6   cohort_sepsis_hour_from_intime_floor        32971 non-null  int64
 7   spesis_hour_delta2                          19154 non-null  float64
 8   spesis_time_delta2                          19154 non-null  str
 9   diff_hours_delta2                           19154 non-null  float64
 10  spesis_hour_sofa2                           25129 non-null  float64
 11  spesis_time_sofa2                           25129 non-null  str
 12  diff_hours_sofa2                            25129 non-null  float64
 13  sepsis3_endtime                             32237 non-null  str
 14  sepsis3_time_hour_floor                     32237 non-null  str
 15  diff_hours_sepsis3                          32237 non-null  float64
dtypes: float64(5), int64(3), str(8)
memory usage: 8.4 MB
None

In [3]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    missing = (
        df.isnull().sum().sort_values(ascending=False)
    )
    display(missing.head(20))

================================================================================
Cohort

subject_id                  0
hadm_id                     0
stay_id                     0
icu_intime                  0
icu_outtime                 0
sepsis_time                 0
suspected_infection_time    0
window_end_uncapped         0
window_end                  0
gender                      0
age                         0
n_hours                     0
dtype: int64

================================================================================
Diagnosis

stay_id        0
hadm_id        0
seq_num        0
icd_code       0
icd_version    0
dtype: int64

================================================================================
Timeseries

crp                     850993
bands                   846016
rate_dobutamine         845221
pao2fio2ratio_novent    843070
rate_dopamine           841195
albumin                 837294
rate_epinephrine        831471
bilirubin_total         825268
bilirubin_max           825251
liver                   825251
pao2fio2ratio_vent      799428
inr                     792118
pt                      792103
respiration             790810
ptt                     790605
lactate                 789034
uo_24hr                 784838
calcium                 782512
magnesium               777808
glucose_lab             776253
dtype: int64

================================================================================
Time Comparison

spesis_hour_delta2                            13817
spesis_time_delta2                            13817
diff_hours_delta2                             13817
spesis_hour_sofa2                              7842
spesis_time_sofa2                              7842
diff_hours_sofa2                               7842
sepsis3_endtime                                 734
sepsis3_time_hour_floor                         734
diff_hours_sepsis3                              734
cohort_sepsis_hour_from_intime_floor              0
suspected_infection_time                          0
suspected_infection_hour_from_intime_floor        0
icu_intime                                        0
icu_intime_floor                                  0
stay_id                                           0
cohort_sepsis_time                                0
dtype: int64

In [21]:
feature_inventory = pd.DataFrame({
    "Features":  [],
    "Dataset":  [],
    "Cliniical Category":  [],
    "Prediction Time Available": [],
    "Leak Risk": [],
    "Decision": [],
    "Notes": []
})
feature_inventory

Empty DataFrame
Columns: [Features, Dataset, Cliniical Category, Prediction Time Available, Leak Risk, Decision, Notes]
Index: []

In [31]:
feature_inventory = pd.DataFrame({
    "Feature": timeseries.columns,
    "Dataset": "Timeseries",
    "Clinical Category": "",
    "Prediction Time Available": "",
    "Leak Risk": "",
    "Decision": "",
    "Notes": ""
})

feature_inventory.head(15)

,Feature,Dataset,Clinical Category,Prediction Time Available,Leak Risk,Decision,Notes
0,stay_id,Timeseries,,,,,
1,hour,Timeseries,,,,,
2,heart_rate,Timeseries,,,,,
3,resp_rate,Timeseries,,,,,
4,temperature,Timeseries,,,,,
5,sbp,Timeseries,,,,,
6,dbp,Timeseries,,,,,
7,mbp,Timeseries,,,,,
8,spo2,Timeseries,,,,,
9,gcs,Timeseries,,,,,
10,urineoutput_last,Timeseries,,,,,
11,urineoutput_sum,Timeseries,,,,,
12,wbc,Timeseries,,,,,
13,hemoglobin,Timeseries,,,,,
14,hematocrit,Timeseries,,,,,

In [33]:
feature_inventory.rename(columns={"features": "Feature"}, inplace=True)

feature_inventory.head()
feature_inventory.loc[
    feature_inventory["Feature"].isin(
        [
            "heart_rate",
            "resp_rate",
            "temperature",
            "sbp",
            "dbp",
            "mbp",
            "spo2",
            "gcs"
        ]
    ),
    ["Clinical Category", "Decision"]
] = [
    "Vital Sign",
    "Keep"
]

In [34]:
feature_inventory.head(15)

,Feature,Dataset,Clinical Category,Prediction Time Available,Leak Risk,Decision,Notes
0,stay_id,Timeseries,,,,,
1,hour,Timeseries,,,,,
2,heart_rate,Timeseries,Vital Sign,,,Keep,
3,resp_rate,Timeseries,Vital Sign,,,Keep,
4,temperature,Timeseries,Vital Sign,,,Keep,
5,sbp,Timeseries,Vital Sign,,,Keep,
6,dbp,Timeseries,Vital Sign,,,Keep,
7,mbp,Timeseries,Vital Sign,,,Keep,
8,spo2,Timeseries,Vital Sign,,,Keep,
9,gcs,Timeseries,Vital Sign,,,Keep,
10,urineoutput_last,Timeseries,,,,,
11,urineoutput_sum,Timeseries,,,,,
12,wbc,Timeseries,,,,,
13,hemoglobin,Timeseries,,,,,
14,hematocrit,Timeseries,,,,,

In [35]:
vital_signs = [
    "heart_rate",
    "resp_rate",
    "temperature",
    "sbp",
    "dbp",
    "mbp",
    "spo2",
    "gcs"
]

In [36]:
feature_inventory.loc[
    feature_inventory["Feature"].isin(vital_signs),
    "Prediction Time Available"
] = "Yes"
feature_inventory.loc[
    feature_inventory["Feature"].isin(vital_signs),
    "Leak Risk"
] = "Low"
feature_inventory.loc[
    feature_inventory["Feature"].isin(vital_signs),
    "Notes"
] = "Core physiological measurements"

In [37]:
feature_inventory.head(15)

,Feature,Dataset,Clinical Category,Prediction Time Available,Leak Risk,Decision,Notes
0,stay_id,Timeseries,,,,,
1,hour,Timeseries,,,,,
2,heart_rate,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
3,resp_rate,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
4,temperature,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
5,sbp,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
6,dbp,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
7,mbp,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
8,spo2,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
9,gcs,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
10,urineoutput_last,Timeseries,,,,,
11,urineoutput_sum,Timeseries,,,,,
12,wbc,Timeseries,,,,,
13,hemoglobin,Timeseries,,,,,
14,hematocrit,Timeseries,,,,,

In [38]:
identifier_features = [
    "stay_id"
]

feature_inventory.loc[
    feature_inventory["Feature"].isin(identifier_features), # .loc helps in updating every feature in identifier feature from feature identifier
    "Clinical Category"
] = "Identifier"

feature_inventory.loc[
    feature_inventory["Feature"].isin(identifier_features),
    "Prediction Time Available"
] = "Yes"

feature_inventory.loc[
    feature_inventory["Feature"].isin(identifier_features),
    "Leak Risk"
] = "None"

feature_inventory.loc[
    feature_inventory["Feature"].isin(identifier_features),
    "Decision"
] = "Remove"

feature_inventory.loc[
    feature_inventory["Feature"].isin(identifier_features),
    "Notes"
] = "Unique patient identifier"

In [42]:
time_features = [ "hour" ]
feature_inventory.loc[ feature_inventory["Feature"].isin(time_features),"Clinical Category"] = "Time"

feature_inventory.loc[ feature_inventory["Feature"].isin(time_features), "Prediction Time Available"] = "yes"
feature_inventory.loc[ feature_inventory["Feature"].isin(time_features), "Leak Risk"] = "Low"
feature_inventory.loc[feature_inventory["Feature"].isin(time_features) , "Decision"] = "keep"
feature_inventory.loc[feature_inventory["Feature"].isin(time_features) ,"Notes"] = "hours since icu admission "
feature_inventory.drop(columns=["Prediction Time available"], inplace=True)
feature_inventory.head(10)

,Feature,Dataset,Clinical Category,Prediction Time Available,Leak Risk,Decision,Notes
0,stay_id,Timeseries,Identifier,Yes,None,Remove,Unique patient identifier
1,hour,Timeseries,Time,yes,Low,keep,hours since icu admission
2,heart_rate,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
3,resp_rate,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
4,temperature,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
5,sbp,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
6,dbp,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
7,mbp,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
8,spo2,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements
9,gcs,Timeseries,Vital Sign,Yes,Low,Keep,Core physiological measurements

In [43]:
print(feature_inventory.columns.tolist())
for col in timeseries.columns:
    print(col)

['Feature', 'Dataset', 'Clinical Category', 'Prediction Time Available', 'Leak Risk', 'Decision', 'Notes']
stay_id
hour
heart_rate
resp_rate
temperature
sbp
dbp
mbp
spo2
gcs
urineoutput_last
urineoutput_sum
wbc
hemoglobin
hematocrit
platelet
creatinine
bun
sodium
potassium
chloride
bicarbonate
calcium
aniongap
glucose_lab
albumin
bilirubin_total
inr
pt
ptt
lactate
bands
crp
magnesium
starttime
endtime
pao2fio2ratio_novent
pao2fio2ratio_vent
rate_epinephrine
rate_norepinephrine
rate_dopamine
rate_dobutamine
meanbp_min
gcs_min
urineoutput_24hr
uo_tm_24hr
uo_24hr
bilirubin_max
creatinine_max
platelet_min
respiration
coagulation
liver
cardiovascular
cns
renal
sofa_score
respiration_24hours
coagulation_24hours
liver_24hours
cardiovascular_24hours
cns_24hours
renal_24hours
sofa_24hours