In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

In [3]:
data_path = Path("../data/hf_external_validation_data/external_validation_data.csv")

df = pd.read_csv(data_path)

print("Dataset Loaded Successfully")

print("Shape :", df.shape)

df.head()

Dataset Loaded Successfully
Shape : (1552210, 44)

,Unnamed: 0,Hour,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,FiO2,pH,PaCO2,SaO2,AST,BUN,Alkalinephos,Calcium,Chloride,Creatinine,Bilirubin_direct,Glucose,Lactate,Magnesium,Phosphate,Potassium,Bilirubin_total,TroponinI,Hct,Hgb,PTT,WBC,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.54,0,NaN,NaN,-0.02,1,0,17072
1,1,1,65.0,100.0,NaN,NaN,72.0,NaN,16.5,NaN,NaN,NaN,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.54,0,NaN,NaN,-0.02,2,0,17072
2,2,2,78.0,100.0,NaN,NaN,42.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.54,0,NaN,NaN,-0.02,3,0,17072
3,3,3,73.0,100.0,NaN,NaN,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.54,0,NaN,NaN,-0.02,4,0,17072
4,4,4,70.0,100.0,NaN,129.0,74.0,69.0,14.0,NaN,NaN,26.0,0.4,NaN,NaN,NaN,NaN,23.0,NaN,9.6,104.0,0.8,NaN,161.0,NaN,1.6,2.1,3.2,NaN,NaN,29.7,9.5,30.6,11.3,NaN,330.0,68.54,0,NaN,NaN,-0.02,5,0,17072

In [4]:
print("Columns:\n")
print(df.columns.tolist())

print("\nUnique Patients :", df["Patient_ID"].nunique())

print("\nRows :", len(df))

print("\nSepsis Distribution:")
print(df["SepsisLabel"].value_counts())

Columns:

['Unnamed: 0', 'Hour', 'HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP', 'Resp', 'EtCO2', 'BaseExcess', 'HCO3', 'FiO2', 'pH', 'PaCO2', 'SaO2', 'AST', 'BUN', 'Alkalinephos', 'Calcium', 'Chloride', 'Creatinine', 'Bilirubin_direct', 'Glucose', 'Lactate', 'Magnesium', 'Phosphate', 'Potassium', 'Bilirubin_total', 'TroponinI', 'Hct', 'Hgb', 'PTT', 'WBC', 'Fibrinogen', 'Platelets', 'Age', 'Gender', 'Unit1', 'Unit2', 'HospAdmTime', 'ICULOS', 'SepsisLabel', 'Patient_ID']

Unique Patients : 40336

Rows : 1552210

Sepsis Distribution:
SepsisLabel
0    1524294
1      27916
Name: count, dtype: int64

In [8]:
exclude_columns = [
    "Unnamed: 0",
    "Patient_ID",
    "SepsisLabel",
    "Hour"
]

numeric_columns = df.select_dtypes(include=np.number).columns #in this only the numeric columns are picked ignoring the text related data

numeric_columns = [
    col for col in numeric_columns
    if col not in exclude_columns
]

print("Number of Physiological Features :", len(numeric_columns))
print(numeric_columns)

Number of Physiological Features : 40
['HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP', 'Resp', 'EtCO2', 'BaseExcess', 'HCO3', 'FiO2', 'pH', 'PaCO2', 'SaO2', 'AST', 'BUN', 'Alkalinephos', 'Calcium', 'Chloride', 'Creatinine', 'Bilirubin_direct', 'Glucose', 'Lactate', 'Magnesium', 'Phosphate', 'Potassium', 'Bilirubin_total', 'TroponinI', 'Hct', 'Hgb', 'PTT', 'WBC', 'Fibrinogen', 'Platelets', 'Age', 'Gender', 'Unit1', 'Unit2', 'HospAdmTime', 'ICULOS']

In [9]:
external_feature_dataset = []

for patient_id, patient in df.groupby("Patient_ID"):

    features = {}

    for column in numeric_columns:

        features[column + "_mean"] = patient[column].mean()
        features[column + "_min"] = patient[column].min()
        features[column + "_max"] = patient[column].max()
        features[column + "_std"] = patient[column].std()
        features[column + "_last"] = patient[column].iloc[-1]

    # Patient label
    features["SepsisLabel"] = patient["SepsisLabel"].max()

    external_feature_dataset.append(features)

In [10]:
### converstion to dataframe
external_feature_dataset = pd.DataFrame(external_feature_dataset)

print("Shape :", external_feature_dataset.shape)

external_feature_dataset.head()

Shape : (40336, 201)

,HR_mean,HR_min,HR_max,HR_std,HR_last,O2Sat_mean,O2Sat_min,O2Sat_max,O2Sat_std,O2Sat_last,Temp_mean,Temp_min,Temp_max,Temp_std,Temp_last,SBP_mean,SBP_min,SBP_max,SBP_std,SBP_last,MAP_mean,MAP_min,MAP_max,MAP_std,MAP_last,DBP_mean,DBP_min,DBP_max,DBP_std,DBP_last,Resp_mean,Resp_min,Resp_max,Resp_std,Resp_last,EtCO2_mean,EtCO2_min,EtCO2_max,EtCO2_std,EtCO2_last,BaseExcess_mean,BaseExcess_min,BaseExcess_max,BaseExcess_std,BaseExcess_last,HCO3_mean,HCO3_min,HCO3_max,HCO3_std,HCO3_last,FiO2_mean,FiO2_min,FiO2_max,FiO2_std,FiO2_last,pH_mean,pH_min,pH_max,pH_std,pH_last,PaCO2_mean,PaCO2_min,PaCO2_max,PaCO2_std,PaCO2_last,SaO2_mean,SaO2_min,SaO2_max,SaO2_std,SaO2_last,AST_mean,AST_min,AST_max,AST_std,AST_last,BUN_mean,BUN_min,BUN_max,BUN_std,BUN_last,Alkalinephos_mean,Alkalinephos_min,Alkalinephos_max,Alkalinephos_std,Alkalinephos_last,Calcium_mean,Calcium_min,Calcium_max,Calcium_std,Calcium_last,Chloride_mean,Chloride_min,Chloride_max,Chloride_std,Chloride_last,Creatinine_mean,Creatinine_min,Creatinine_max,Creatinine_std,Creatinine_last,Bilirubin_direct_mean,Bilirubin_direct_min,Bilirubin_direct_max,Bilirubin_direct_std,Bilirubin_direct_last,Glucose_mean,Glucose_min,Glucose_max,Glucose_std,Glucose_last,Lactate_mean,Lactate_min,Lactate_max,Lactate_std,Lactate_last,Magnesium_mean,Magnesium_min,Magnesium_max,Magnesium_std,Magnesium_last,Phosphate_mean,Phosphate_min,Phosphate_max,Phosphate_std,Phosphate_last,Potassium_mean,Potassium_min,Potassium_max,Potassium_std,Potassium_last,Bilirubin_total_mean,Bilirubin_total_min,Bilirubin_total_max,Bilirubin_total_std,Bilirubin_total_last,TroponinI_mean,TroponinI_min,TroponinI_max,TroponinI_std,TroponinI_last,Hct_mean,Hct_min,Hct_max,Hct_std,Hct_last,Hgb_mean,Hgb_min,Hgb_max,Hgb_std,Hgb_last,PTT_mean,PTT_min,PTT_max,PTT_std,PTT_last,WBC_mean,WBC_min,WBC_max,WBC_std,WBC_last,Fibrinogen_mean,Fibrinogen_min,Fibrinogen_max,Fibrinogen_std,Fibrinogen_last,Platelets_mean,Platelets_min,Platelets_max,Platelets_std,Platelets_last,Age_mean,Age_min,Age_max,Age_std,Age_last,Gender_mean,Gender_min,Gender_max,Gender_std,Gender_last,Unit1_mean,Unit1_min,Unit1_max,Unit1_std,Unit1_last,Unit2_mean,Unit2_min,Unit2_max,Unit2_std,Unit2_last,HospAdmTime_mean,HospAdmTime_min,HospAdmTime_max,HospAdmTime_std,HospAdmTime_last,ICULOS_mean,ICULOS_min,ICULOS_max,ICULOS_std,ICULOS_last,SepsisLabel
0,101.571429,76.0,117.0,9.594378,84.0,91.477273,85.0,100.0,3.460667,85.0,36.778000,36.11,37.44,0.421078,NaN,126.809524,78.0,181.0,22.422482,78.0,87.261905,44.00,141.33,21.270465,44.0,NaN,NaN,NaN,NaN,NaN,24.820000,17.0,32.0,4.106689,18.0,NaN,NaN,NaN,NaN,NaN,20.714286,18.0,24.0,2.13809,NaN,46.500000,45.0,48.0,2.121320,NaN,0.282500,0.25,0.3,0.023629,NaN,7.347143,7.31,7.40,0.031472,NaN,95.333333,86.0,100.0,6.022181,NaN,86.500000,78.0,91.0,5.802298,NaN,16.000000,16.0,16.0,NaN,NaN,18.000000,14.0,22.0,5.656854,NaN,98.0,98.0,98.0,NaN,NaN,9.450000,9.3,9.6,0.212132,NaN,85.000000,85.0,85.0,0.00000,NaN,0.700000,0.7,0.7,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,163.000000,133.0,193.0,42.426407,NaN,NaN,NaN,NaN,NaN,NaN,2.100000,2.0,2.2,0.141421,NaN,3.500000,3.3,3.7,0.282843,NaN,4.200000,3.8,4.6,0.565685,NaN,0.300000,0.3,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.700000,36.2,37.2,0.707107,NaN,12.350000,12.2,12.5,0.212132,NaN,NaN,NaN,NaN,NaN,NaN,10.200000,5.7,14.7,6.363961,NaN,NaN,NaN,NaN,NaN,NaN,327.500000,317.0,338.0,14.849242,NaN,83.14,83.14,83.14,2.868859e-14,83.14,0.0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.03,-0.03,-0.03,3.502025e-18,-0.03,27.5,1,54,15.732133,54,0
1,60.954545,54.0,94.0,8.144395,55.0,97.000000,94.0,100.0,2.138090,95.0,36.165000,36.00,36.44,0.151625,NaN,136.600000,114.0,194.0,20.180613,NaN,66.704545,50.50,116.00,14.720134,51.0,44.066667,36.0,66.0,7.095941,NaN,14.236842,9.0,27.0,4.667763,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,22.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.900000,7.9,7.9,NaN,NaN,113.000000,113.0,113.0,NaN,NaN,2.500000,2.5,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.000000,78.0,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.500000,2.5,2.5,NaN,NaN,4.400000,4.4,4.4,NaN,NaN,5.100000,5.1,5.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.800000,27.8,27.8,NaN,NaN,9.700000,9.7,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,11.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.000000,158.0,158.0,NaN,NaN,75.91,75.91,75.91,2.906048e-14,75.91,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,-98.60,-98.60,-98.60,2.906048e-14,-98.60,12.0,1,23,6.782330,23,0
2,79.611111,68.0,93.0,6.714036,78.0,95.431818,91.0,99.0,1.655122,97.0,37.609375,36.89,38.61,0.565597,NaN,140.033333,122.0,159.0,8.954684,138.0,81.048000,62.67,99.00,7.854301,83.0,54.392857,44.0,69.0,5.258600,53.0,25.633333,17.0,40.0,4.247192,26.0,NaN,NaN,NaN,NaN,NaN,6.500000,5.0,8.0,2.12132,NaN,30.666667,29.0,32.0,1.527525,NaN,0.642857,0.50,0.8,0.151186,NaN,7.496667,7.49,7.51,0.011547,NaN,39.500000,38.0,41.0,2.121320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.666667,25.0,31.0,3.214550,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,10.9,11.1,0.100000,NaN,99.000000,98.0,100.0,1.00000,NaN,0.866667,0.8,0.9,0.057735,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,51.0,130.0,41.581246,NaN,NaN,NaN,NaN,NaN,NaN,2.433333,2.4,2.5,0.057735,NaN,2.533333,2.3,2.9,0.321455,NaN,3.775000,3.4,4.1,0.287228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.650000,26.2,32.1,2.678930,NaN,9.633333,8.8,11.0,1.193035,NaN,30.0,29.5,30.5,0.707107,NaN,9.000000,8.3,10.0,0.888819,NaN,NaN,NaN,NaN,NaN,NaN,479.666667,465.0,488.0,12.741010,NaN,45.82,45.82,45.82,0.000000e+00,45.82,0.0,0,0,0.0,0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-1195.71,-1195.71,-1195.71,0.000000e+00,-1195.71,24.5,1,48,14.000000,48,0
3,102.444444,93.0,113.0,6.337212,NaN,98.203704,95.5,100.0,1.449531,NaN,36.455000,36.06,36.78,0.262507,NaN,113.019231,90.0,132.5,9.013857,NaN,67.147308,34.00,84.00,10.048494,NaN,51.428571,44.0,61.5,6.129554,NaN,18.884615,14.0,26.0,3.742480,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,0.00000,NaN,22.000000,22.0,22.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,7.390000,7.36,7.41,0.026458,NaN,43.000000,41.0,45.0,2.828427,NaN,97.833333,97.5,98.0,0.288675,NaN,NaN,NaN,NaN,NaN,NaN,16.500000,14.0,19.0,3.535534,NaN,NaN,NaN,NaN,NaN,NaN,8.200000,8.2,8.2,NaN,NaN,106.500000,105.0,108.0,2.12132,NaN,0.800000,0.8,0.8,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,135.333333,69.0,253.0,102.177949,NaN,NaN,NaN,NaN,NaN,NaN,2.050000,1.7,2.4,0.494975,NaN,3.800000,3.8,3.8,NaN,NaN,4.433333,4.0,5.0,0.513160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.800000,24.0,27.6,2.545584,NaN,8.300000,8.3,8.3,NaN,NaN,21.8,21.3,22.3,0.707107,NaN,7.600000,7.6,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182.000000,144.0,220.0,53.740115,NaN,65.71,65.71,65.71,1.446239e-14,65.71,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,-8.77,-8.77,-8.77,1.807799e-15,-8.77,15.0,1,29,8.514693,29,0
4,73.916667,61.0,88.0,7.586697,NaN,97.500000,96.0,99.0,0.741620,NaN,36.992222,36.22,37.33,0.423520,NaN,132.770833,114.0,150.0,9.908252,NaN,87.088235,73.00,103.00,8.631764,NaN,NaN,NaN,NaN,NaN,NaN,16.500000,14.0,21.0,1.788854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.666667,24.0,28.0,2.081666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.666667,16.0,30.0,8.082904,NaN,7.333333,6.0,9.0,1.527525,NaN,69.0,62.0,80.0,9.643651,NaN,8.166667,7.8,8.5,0.351188,NaN,105.333333,105.0,106.0,0.57735,NaN,0.633333,0.6,0.7,0.057735,NaN,NaN,NaN,NaN,NaN,NaN,123.000000,103.0,138.0,18.027756,NaN,NaN,NaN,NaN,NaN,NaN,2.200000,1.9,2.5,0.300000,NaN,2.866667,2.8,3.0,0.115470,NaN,3.566667,3.1,4.0,0.450925,NaN,0.566667,0.5,0.6,0.057735,NaN,NaN,NaN,NaN,NaN,NaN,42.133333,39.7,45.7,3.156475,NaN,14.700000,14.2,15.5,0.700000,NaN,29.0,29.0,29.0,0.000000,NaN,6.933333,4.7,8.1,1.934770,NaN,NaN,NaN,NaN,NaN,NaN,279.000000,273.0,288.0,7.937254,NaN,28.09,28.09,28.09,0.000000e+00,28.09,1.0,1,1,0.0,1,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-0.05,-0.05,-0.05,7.012323e-18,-0.05,25.5,2,49,14.000000,49,0

In [11]:
missing = (
    external_feature_dataset
    .isnull()
    .mean()
    .sort_values(ascending=False) * 100
)

missing.head(20)

Bilirubin_direct_last    99.888437
Fibrinogen_last          99.672749
TroponinI_last           99.543832
Bilirubin_total_last     99.253768
AST_last                 99.201706
Alkalinephos_last        99.199226
Lactate_last             98.948830
Bilirubin_direct_std     98.787683
SaO2_last                98.537287
PTT_last                 98.358786
EtCO2_last               98.019139
BaseExcess_last          97.657180
Phosphate_last           97.634867
PaCO2_last               97.619992
HCO3_last                97.533221
Chloride_last            97.347283
pH_last                  96.806823
Calcium_last             96.782031
Platelets_last           96.715093
Creatinine_last          96.501884
dtype: float64

In [12]:
output_path = Path("../data/processed")
output_path.mkdir(exist_ok=True)

external_feature_dataset.to_csv(
    output_path / "external_feature_dataset.csv",
    index=False
)

print("External feature dataset saved successfully!")

External feature dataset saved successfully!